services:
  postgres:
    image: postgres:17
    container_name: project_lomo_postgres
    env_file: .env-postgres
    environment:
      POSTGRES_DB: lomo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [CMD-SHELL, pg_isready -U postgres]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    build: apps/backend
    image: backend
    container_name: project_lomo_backend
    env_file: .env-backend
    environment:
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      DJANGO_SUPERUSER_PASSWORD: admin
    ports:
      - "8000:8000"
    depends_on:
      - postgres


volumes:
  postgres_data:
